services:
  # 1. Твій Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 2. FastAPI (Python)
  ml_api:
    build: ./TrustGuard.ML   # <-- Ось тут Docker піде в папку ML
    command: uvicorn main:app --host 0.0.0.0 --port 8000  # <--- ДОДАЙ ОСЬ ЦЕЙ РЯДОК
    ports:
      - "8000:8000"
    depends_on:
      - redis

  # 3. Celery Worker (Python)
  ml_worker:
    build: ./TrustGuard.ML   # <-- І ось тут теж!
    command: celery -A worker worker --loglevel=info
    depends_on:
      - redis
      - ml_api

  # 4. Твій сайт на C#
  web_app:
    build:
      context: .  
      dockerfile: TrustGuard.Web/Dockerfile # <-- А тут Docker піде в папку Web
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Кажемо C# стукати до FastAPI по внутрішній мережі Docker
      - PythonApiUrl=http://ml_api:8000 
    depends_on:
      - ml_api